import * as THREE from 'three';
const clamp=THREE.MathUtils.clamp,hash=n=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x);};
export function createImpactVfx({scene,capacity=224}={}){
 const count=Math.max(64,Math.floor(capacity)),positions=new Float32Array(count*3),velocities=new Float32Array(count*3),alphas=new Float32Array(count),sizes=new Float32Array(count),shades=new Float32Array(count),ages=new Float32Array(count),lives=new Float32Array(count),active=new Uint8Array(count);
 const geometry=new THREE.BufferGeometry(),pa=new THREE.BufferAttribute(positions,3),aa=new THREE.BufferAttribute(alphas,1),sa=new THREE.BufferAttribute(sizes,1),sha=new THREE.BufferAttribute(shades,1);for(const a of [pa,aa,sa,sha])a.setUsage(THREE.DynamicDrawUsage);geometry.setAttribute('position',pa);geometry.setAttribute('aAlpha',aa);geometry.setAttribute('aSize',sa);geometry.setAttribute('aShade',sha);
 const material=new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,vertexShader:['attribute float aAlpha;','attribute float aSize;','attribute float aShade;','varying float vAlpha;','varying float vShade;','void main(){vAlpha=aAlpha;vShade=aShade;vec4 mv=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=aSize*clamp(22.0/max(1.0,-mv.z),.55,2.4);}'].join('\n'),fragmentShader:['varying float vAlpha;','varying float vShade;','void main(){vec2 p=gl_PointCoord-.5;float d=length(p);if(d>.5)discard;float body=1.0-smoothstep(.34,.50,d);float rim=1.0-smoothstep(.08,.42,d);float spec=pow(max(0.0,1.0-length(p-vec2(-.16,.17))/.20),4.0);vec3 color=mix(vec3(.115,.004,.010),vec3(.38,.010,.024),clamp(vShade,0.0,1.0));color+=spec*vec3(.20,.035,.040);float alpha=vAlpha*body*(.80+.20*rim);if(alpha<.006)discard;gl_FragColor=vec4(color,alpha);','#include <tonemapping_fragment>','#include <colorspace_fragment>','}'].join('\n')});
 const points=new THREE.Points(geometry,material);points.name='impact-liquid-splash-vfx';points.frustumCulled=false;points.renderOrder=12;scene?.add(points);let cursor=0,serial=0;
 function spawn(x,y,z,vx,vy,vz,size,life,alpha,shade){const i=cursor++%count,k=i*3;active[i]=1;ages[i]=0;lives[i]=Math.max(.18,life);positions[k]=x;positions[k+1]=y;positions[k+2]=z;velocities[k]=vx;velocities[k+1]=vy;velocities[k+2]=vz;sizes[i]=size;alphas[i]=alpha;shades[i]=shade;serial++;}
 function burst({x=0,y=.5,z=0,direction=1,speed=40,severity=1}={}){const strength=clamp(Number(severity)||1,.35,1.25),speed01=clamp((Number(speed)-35)/50,0,1),amount=Math.round((42+speed01*32)*strength);for(let n=0;n<amount;n++){const r=hash(serial+n*5+11),r2=hash(serial+n*7+29),r3=hash(serial+n*13+3),angle=(r-.5)*Math.PI*1.85,radial=(2.0+r2*5.6)*(.72+strength*.38),away=(Number(direction)||1)*(1.2+r3*3.1)*(.65+speed01*.55);spawn(x+(r-.5)*.34,y+(r2-.5)*.24,z+(r3-.5)*.24,Math.cos(angle)*radial+away,2.2+r2*(5.4+speed01*3.0),Math.sin(angle)*radial+(r3-.5)*2.2,5.2+r*8.6,.42+r2*.64,.48+r3*.42,.25+r2*.75);}pa.needsUpdate=aa.needsUpdate=sa.needsUpdate=sha.needsUpdate=true;}
 function update(dt){let pd=false,ad=false,sd=false;for(let i=0;i<count;i++){if(!active[i])continue;ages[i]+=dt;if(ages[i]>=lives[i]){active[i]=0;alphas[i]=0;ad=true;continue;}const k=i*3;positions[k]+=velocities[k]*dt;positions[k+1]+=velocities[k+1]*dt;positions[k+2]+=velocities[k+2]*dt;velocities[k]*=Math.pow(.30,dt);velocities[k+1]-=12.4*dt;velocities[k+2]*=Math.pow(.34,dt);const t=ages[i]/lives[i];alphas[i]=Math.min(alphas[i],(1-t)*(1-t)*.92);sizes[i]*=1+dt*.12;if(positions[k+1]<-1.4){active[i]=0;alphas[i]=0;}pd=ad=sd=true;}if(pd)pa.needsUpdate=true;if(ad)aa.needsUpdate=true;if(sd)sa.needsUpdate=true;}
 function reset(){active.fill(0);alphas.fill(0);ages.fill(0);lives.fill(0);aa.needsUpdate=true;}function dispose(){scene?.remove(points);geometry.dispose();material.dispose();}return {burst,update,reset,dispose,points};
}
