import {SKI_TUNING as T} from './gameplayTuning.js';
import {getRideProfile} from './rideMode.js';
import {resolveCourseEdgeContact} from './edgeContact.js';
import {updateJumpAssist,tryManualJump,stepAir,launchRamp} from './skiPhysics.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const lerp=(a,b,t)=>a+(b-a)*clamp(t,0,1);
const damp=(a,b,r,dt)=>b+(Number(a||0)-b)*Math.exp(-Math.max(0,r)*Math.max(0,Number(dt)||0));

export const SKATEBOARD_LANDING=Object.freeze({CLEAN:'clean',SKETCHY:'sketchy',HARD:'hard',FAILED:'failed'});
export const SKATEBOARD_ANIMATION_STATE=Object.freeze({IDLE:'idle',PUSH:'push',CARVE_LEFT:'carveLeft',CARVE_RIGHT:'carveRight',POWERSLIDE:'powerslide',OLLIE_COMPRESSION:'ollieCompression',OLLIE_POP:'olliePop',AIR:'air',KICKFLIP:'kickflip',HEELFLIP:'heelflip',SHOVEIT:'shoveit',MANUAL:'manual',NOSE_MANUAL:'noseManual',GRIND:'grind',LAND:'land',HARD_LAND:'hardLand',CRASH:'crash'});
export const SKATEBOARD_TUNING=Object.freeze({
  LOW_SPEED_STEER:1.18,HIGH_SPEED_STEER:.66,TRUCK_RESPONSE_LOW:11.8,TRUCK_RESPONSE_HIGH:7,
  TURN_RATE_LOW:1.24,TURN_RATE_HIGH:.88,HEADING_LOW:.42,HEADING_HIGH:.29,LATERAL_LOW:.43,LATERAL_HIGH:.31,
  ROLLING_GRIP_LOW:.98,ROLLING_GRIP_HIGH:.86,OIL_GRIP:.34,WET_GRIP:.76,POWER_GRIP:1.08,
  POWERSLIDE_SPEED01:.16,POWERSLIDE_STEER:.72,POWERSLIDE_EDGE:.52,POWERSLIDE_GRIP:.36,POWERSLIDE_FRICTION:.12,
  OLLIE_POP:9.15,NOLLIE_POP:8.65,POWER_POP:1.12,MANUAL_THRESHOLD:.52,MANUAL_ENTRY:.10,MANUAL_FAIL:.96,
  GRIND_CAPTURE:.72,GRIND_ANGLE:34,GRIND_MIN_SPEED:10,GRIND_FRICTION:.045,GRIND_FAIL:.98,GRIND_MIN_DURATION:.08,
  DISPLAY_MIN_KMH:24,DISPLAY_MAX_KMH:68
});

function fresh(){return {native:true,steeringSensitivity:1,truckFront:0,truckRear:0,rollingGrip:1,lateralGrip:1,slip:0,powerslide:false,powerslideAmount:0,manualMode:'',manualDuration:0,manualBalance:0,grindState:'',grindTargetId:'',grindDuration:0,grindBalance:0,olliePhase:'idle',ollieCharge:0,wheelContacts:4,animationState:'idle',comboContinuation:false,lastLanding:'clean',eventId:0,lastEvent:null,events:[]};}
export function ensureSkateboardState(state){if(!state.skate)state.skate=fresh();return state.skate;}
export function resetSkateboardState(state){const id=state.skate?.eventId||0;state.skate=fresh();state.skate.eventId=id;state.grinding=false;return state.skate;}
export function emitSkateboardEvent(state,type,payload={}){const s=ensureSkateboardState(state),e={id:++s.eventId,type,time:Number(state.time)||0,...payload};s.lastEvent=e;s.events.push(e);if(s.events.length>24)s.events.shift();return e;}
export function consumeSkateboardEvents(state){const s=ensureSkateboardState(state),out=s.events.slice();s.events.length=0;return out;}
export function getSkateboardDisplaySpeedRange(){return {minKmh:SKATEBOARD_TUNING.DISPLAY_MIN_KMH,maxKmh:SKATEBOARD_TUNING.DISPLAY_MAX_KMH};}
export function skateboardDisplaySpeedKmh(speed,rideMode='snowboard'){const p=getRideProfile(rideMode),x=clamp((Number(speed)-p.baseSpeed)/Math.max(.001,p.maxSpeed-p.baseSpeed),0,1);return Math.round(lerp(SKATEBOARD_TUNING.DISPLAY_MIN_KMH,SKATEBOARD_TUNING.DISPLAY_MAX_KMH,Math.pow(x,.82)));}
export function skateboardDisplaySpeed(speed,rideMode='snowboard'){return skateboardDisplaySpeedKmh(speed,rideMode)/3.6;}

function animate(state,steer=0){const s=ensureSkateboardState(state);if(s.grindState==='active')s.animationState='grind';else if(state.air)s.animationState='air';else if(s.powerslide)s.animationState='powerslide';else if(s.manualMode)s.animationState=s.manualMode;else if(Math.abs(steer)>.12)s.animationState=steer<0?'carveLeft':'carveRight';else s.animationState=(state.speed||0)>(state.baseSpeed||0)*1.02?'push':'idle';return s.animationState;}

export function stepSkateboardSteering(state,input,dt,{powered=false,wetness=0}={}){
  const s=ensureSkateboardState(state),p=getRideProfile(state.rideMode),span=Math.max(.001,p.maxSpeed-p.baseSpeed),speed01=clamp((state.speed-p.baseSpeed)/span,0,1),steer=Math.abs(input)<T.INPUT_DEADZONE?0:clamp(input,-1,1),frame=Math.max(0,Number(dt)||0),oil=clamp((state.oilSlipTime||0)/Math.max(.001,T.OIL_SLIP_SECONDS),0,1);
  state.landingGripLoss=Math.max(0,(state.landingGripLoss||0)-frame*2.5);state.oilSlipTime=Math.max(0,(state.oilSlipTime||0)-frame);
  if(state.grinding){state.edge=damp(state.edge,steer*.34,8.2,frame);s.truckFront=state.edge;s.truckRear=-state.edge*.82;s.powerslide=false;s.animationState='grind';return {grinding:true};}
  s.steeringSensitivity=lerp(SKATEBOARD_TUNING.LOW_SPEED_STEER,SKATEBOARD_TUNING.HIGH_SPEED_STEER,speed01);
  state.edge=damp(state.edge,clamp(steer*s.steeringSensitivity,-1,1),lerp(SKATEBOARD_TUNING.TRUCK_RESPONSE_LOW,SKATEBOARD_TUNING.TRUCK_RESPONSE_HIGH,speed01)*(oil>.05?.72:1),frame);s.truckFront=state.edge;s.truckRear=-state.edge*.82;
  if(state.air){state.heading=clamp(state.heading+state.edge*frame*lerp(.82,.56,speed01),-SKATEBOARD_TUNING.HEADING_HIGH,SKATEBOARD_TUNING.HEADING_HIGH);state.vx=damp(state.vx,Math.sin(state.heading)*state.speed*lerp(.22,.16,speed01),3.7,frame);state.x=clamp(state.x+state.vx*frame,-T.PLAYER_BOUNDARY_HALF_WIDTH,T.PLAYER_BOUNDARY_HALF_WIDTH);Object.assign(s,{wheelContacts:0,rollingGrip:0,lateralGrip:0,slip:0,powerslide:false});state.grip=0;animate(state,steer);return null;}
  s.wheelContacts=4;const landing=lerp(1,.54,clamp(state.landingGripLoss||0,0,1)),surface=lerp(1,SKATEBOARD_TUNING.WET_GRIP,clamp(wetness,0,1))*lerp(1,SKATEBOARD_TUNING.OIL_GRIP,oil)*landing*(powered?SKATEBOARD_TUNING.POWER_GRIP:1),rolling=clamp(lerp(SKATEBOARD_TUNING.ROLLING_GRIP_LOW,SKATEBOARD_TUNING.ROLLING_GRIP_HIGH,speed01)*surface,.22,1.08),wanted=speed01>=SKATEBOARD_TUNING.POWERSLIDE_SPEED01&&Math.abs(steer)>=SKATEBOARD_TUNING.POWERSLIDE_STEER&&Math.abs(state.edge)>=SKATEBOARD_TUNING.POWERSLIDE_EDGE&&oil<.82,before=s.powerslide;
  s.powerslideAmount=damp(s.powerslideAmount,wanted?1:0,wanted?8.5:5.5,frame);s.powerslide=s.powerslideAmount>.28;if(s.powerslide&&!before)emitSkateboardEvent(state,'powerslideStart');if(!s.powerslide&&before)emitSkateboardEvent(state,'powerslideEnd');
  s.rollingGrip=rolling;s.lateralGrip=clamp(lerp(rolling,SKATEBOARD_TUNING.POWERSLIDE_GRIP,s.powerslideAmount),.18,1.08);s.slip=clamp((1-s.lateralGrip)*.75+s.powerslideAmount*.55+oil*.48,0,1);state.grip=s.lateralGrip;state.carveLoad=damp(state.carveLoad,Math.abs(state.edge)*(.72+speed01*.24),7.5,frame);
  const hlim=lerp(SKATEBOARD_TUNING.HEADING_LOW,SKATEBOARD_TUNING.HEADING_HIGH,speed01),turn=state.edge*lerp(SKATEBOARD_TUNING.TURN_RATE_LOW,SKATEBOARD_TUNING.TURN_RATE_HIGH,speed01)*(.72+s.lateralGrip*.38);state.turnRate=damp(state.turnRate,turn,6.8,frame);state.heading=clamp(state.heading+state.turnRate*frame,-hlim,hlim);if(!steer){state.heading=damp(state.heading,0,3.8,frame);state.turnRate=damp(state.turnRate,0,4.2,frame);}
  let targetVx=Math.sin(state.heading)*state.speed*lerp(SKATEBOARD_TUNING.LATERAL_LOW,SKATEBOARD_TUNING.LATERAL_HIGH,speed01)*(s.powerslide?1.22:1);state.vx=damp(state.vx,targetVx,lerp(8.8,6.4,speed01)*lerp(.5,1,s.lateralGrip),frame);state.x=clamp(state.x+state.vx*frame,-T.PLAYER_BOUNDARY_HALF_WIDTH,T.PLAYER_BOUNDARY_HALF_WIDTH);if(s.powerslide)state.speed=Math.max(p.baseSpeed*.9,state.speed*(1-SKATEBOARD_TUNING.POWERSLIDE_FRICTION*s.powerslideAmount*frame));
  const edgeScrape=resolveCourseEdgeContact(state,frame,{profile:p});animate(state,steer);return edgeScrape?{edgeScrape,powerslide:s.powerslide,slip:s.slip}:{powerslide:s.powerslide,slip:s.slip};
}

export function updateSkateboardJumpAssist(state,pressed,dt,held=pressed){const s=ensureSkateboardState(state);updateJumpAssist(state,pressed,dt,held);if(!state.air&&held){s.ollieCharge=clamp(s.ollieCharge+dt*7,0,1);s.olliePhase='compression';s.animationState='ollieCompression';}else if(!state.air){s.ollieCharge=damp(s.ollieCharge,0,10,dt);if(s.olliePhase!=='landing')s.olliePhase='idle';}return s.olliePhase;}
export function trySkateboardOllie(state,groundY,{powered=false,nollie=false}={}){const s=ensureSkateboardState(state),nose=s.manualMode==='noseManual';if(!tryManualJump(state,groundY))return false;const isNollie=nollie||nose,pop=(isNollie?SKATEBOARD_TUNING.NOLLIE_POP:SKATEBOARD_TUNING.OLLIE_POP)*lerp(.91,1.06,s.ollieCharge)*(powered?SKATEBOARD_TUNING.POWER_POP:1);state.vy=Math.max(state.vy,pop);state.jumpVelocity=state.vy;state.jumpSource=isNollie?'nollie':'ollie';state.jumpProfile=state.jumpSource;Object.assign(s,{olliePhase:'pop',ollieCharge:0,manualMode:'',manualDuration:0,animationState:'olliePop'});emitSkateboardEvent(state,'tailPop',{nollie:isNollie,powered:!!powered,velocity:state.vy});return true;}
export function stepSkateboardAir(state,dt,groundY){const landing=stepAir(state,dt,groundY),s=ensureSkateboardState(state);if(state.air){s.olliePhase='air';s.wheelContacts=0;s.animationState='air';}if(!landing.landed)return landing;const impact=Math.abs(landing.impact||0),align=Math.abs(state.heading||0),lat=Math.abs(state.vx||0);let q='clean';if(impact>=15.8||align>=.72||lat>=11.5)q='failed';else if(impact>=12.2||align>=.48||lat>=8.2)q='hard';else if(impact>=8.4||align>=.22||lat>=5.2)q='sketchy';s.lastLanding=q;s.wheelContacts=q==='failed'?2:4;s.olliePhase='landing';s.animationState=q==='hard'||q==='failed'?'hardLand':'land';landing.quality=q;landing.failed=q==='failed';emitSkateboardEvent(state,q==='hard'||q==='failed'?'hardLand':'land',{quality:q,impact,alignment:align,lateralVelocity:lat,wheelContacts:s.wheelContacts});if(q==='sketchy'){state.speed*=.965;state.landingGripLoss=Math.max(state.landingGripLoss||0,.34);}else if(q==='hard'){state.speed*=.92;state.landingGripLoss=Math.max(state.landingGripLoss||0,.66);}else if(q==='failed'){state.speed*=.84;state.landingGripLoss=1;}return landing;}
export function launchSkateboardRamp(state,groundY,{powered=false}={}){if(!launchRamp(state,groundY))return false;const s=ensureSkateboardState(state);if(powered){state.vy*=1.06;state.jumpVelocity=state.vy;}Object.assign(s,{olliePhase:'air',wheelContacts:0,animationState:'air'});emitSkateboardEvent(state,'tailPop',{ramp:true,powered:!!powered});return true;}

export function updateSkateboardManual(state,{verticalIntent=0,dt=1/60,powered=false}={}){const s=ensureSkateboardState(state),v=clamp(verticalIntent,-1,1),wanted=Math.abs(v)>=SKATEBOARD_TUNING.MANUAL_THRESHOLD?(v<0?'noseManual':'manual'):'';if(state.air||state.grinding||s.powerslide){if(s.manualMode)emitSkateboardEvent(state,'manualEnd',{mode:s.manualMode});Object.assign(s,{manualMode:'',manualDuration:0,manualBalance:0,comboContinuation:false});return s;}if(!wanted){if(s.manualMode)emitSkateboardEvent(state,'manualEnd',{mode:s.manualMode,duration:s.manualDuration});Object.assign(s,{manualMode:'',manualDuration:0,comboContinuation:false});return s;}if(!s.manualMode){s.manualDuration+=dt;if(s.manualDuration<SKATEBOARD_TUNING.MANUAL_ENTRY)return s;s.manualMode=wanted;s.manualDuration=0;s.manualBalance=0;emitSkateboardEvent(state,'manualStart',{mode:wanted});}else if(s.manualMode!==wanted){emitSkateboardEvent(state,'manualEnd',{mode:s.manualMode});s.manualMode=wanted;s.manualDuration=0;s.manualBalance=0;emitSkateboardEvent(state,'manualStart',{mode:wanted});}s.manualDuration+=dt;s.manualBalance=clamp(damp(s.manualBalance,0,2.8*(powered?1.25:1),dt)+(state.edge||0)*.36*dt,-1,1);s.comboContinuation=true;s.animationState=s.manualMode;if(Math.abs(s.manualBalance)>=SKATEBOARD_TUNING.MANUAL_FAIL){emitSkateboardEvent(state,'manualEnd',{mode:s.manualMode,reason:'balance'});Object.assign(s,{manualMode:'',manualDuration:0,manualBalance:0,comboContinuation:false});state.landingGripLoss=Math.max(state.landingGripLoss||0,.28);}return s;}

const point=p=>({x:Number(p?.x)||0,y:Number(p?.y)||0,z:Number(p?.z)||0});
const closest=(p,a,b)=>{const x=b.x-a.x,z=b.z-a.z,l=x*x+z*z,t=l?clamp(((p.x-a.x)*x+(p.z-a.z)*z)/l,0,1):0;return {x:a.x+x*t,y:a.y+(b.y-a.y)*t,z:a.z+z*t,t};};
export function createGrindTarget({id,start,end,captureRadius=SKATEBOARD_TUNING.GRIND_CAPTURE,allowedTricks=['50-50','5-0','NOSEGRIND','BOARDSLIDE','LIPSLIDE'],getEndpoints=null}={}){if(!id)throw new Error('grind target requires id');if(!getEndpoints&&(!start||!end))throw new Error('grind target requires endpoints');return {id:String(id),start:start?point(start):null,end:end?point(end):null,captureRadius:Math.max(.1,Number(captureRadius)||SKATEBOARD_TUNING.GRIND_CAPTURE),allowedTricks:[...new Set(allowedTricks)],getEndpoints:typeof getEndpoints==='function'?getEndpoints:null};}
export function createGrindSystem(){const targets=new Map();let active=null;const ends=t=>{const d=t.getEndpoints?.();return d?.start&&d?.end?{start:point(d.start),end:point(d.end)}:{start:t.start,end:t.end};};function register(t){const n=createGrindTarget(t);targets.set(n.id,n);return n;}function unregister(id){if(active?.target.id===String(id))active=null;return targets.delete(String(id));}function reset(){active=null;}function clear(){active=null;targets.clear();}
  function tryEnter(state,{playerZ=0,preferredTrick='50-50',powered=false}={}){if(active||!state.air||state.speed<SKATEBOARD_TUNING.GRIND_MIN_SPEED)return false;const p=point({x:state.x,y:state.y,z:playerZ}),vx=Number(state.vx)||0,vz=-Math.max(.001,state.speed||0),vl=Math.hypot(vx,vz)||1;let best=null;for(const target of targets.values()){const e=ends(target);if(!e.start||!e.end)continue;const c=closest(p,e.start,e.end),r=target.captureRadius*(powered?1.18:1),dx=p.x-c.x,dz=p.z-c.z;if(dx*dx+dz*dz>r*r||Math.abs(p.y-c.y)>r*1.35)continue;const tx=e.end.x-e.start.x,tz=e.end.z-e.start.z,tl=Math.hypot(tx,tz)||1,dot=(vx*tx+vz*tz)/(vl*tl),angle=Math.acos(clamp(Math.abs(dot),-1,1))*180/Math.PI;if(angle>SKATEBOARD_TUNING.GRIND_ANGLE+(powered?8:0))continue;const score=dx*dx+dz*dz+angle*.004;if(!best||score<best.score)best={target,e,c,score,direction:dot>=0?1:-1};}if(!best)return false;const trick=best.target.allowedTricks.includes(preferredTrick)?preferredTrick:best.target.allowedTricks[0];active={target:best.target,trick,direction:best.direction,balance:0,duration:0,progress:best.c.t};const s=ensureSkateboardState(state);Object.assign(s,{grindState:'active',grindTargetId:best.target.id,grindDuration:0,grindBalance:0,comboContinuation:true,animationState:'grind'});state.grinding=true;state.air=false;state.grounded=false;state.vy=0;state.x=best.c.x;state.y=best.c.y+.12;emitSkateboardEvent(state,'grindStart',{targetId:best.target.id,trick});return true;}
  function exit(state,reason='natural-exit'){if(!active)return {active:false,reason};const a=active,s=ensureSkateboardState(state),completed=a.duration>=SKATEBOARD_TUNING.GRIND_MIN_DURATION&&reason!=='balance-fail',points=completed?Math.max(25,Math.round(a.duration*140)):0;state.grinding=false;Object.assign(s,{grindState:'',grindTargetId:'',grindBalance:0,comboContinuation:completed});if(points){state.score=(state.score||0)+points;state.combo=Math.max(1,Number(state.combo)||1);}if(reason!=='jump-off'){state.air=true;state.grounded=false;state.jumping=true;state.jumpSource='grind';state.vy=reason==='balance-fail'?-1.4:0;state.jumpVelocity=state.vy;}emitSkateboardEvent(state,'grindEnd',{targetId:a.target.id,trick:a.trick,duration:a.duration,reason,points,completed});active=null;return {active:false,reason,trick:a.trick,duration:a.duration,points,completed};}
  function step(state,dt,{steer=0,powered=false}={}){if(!active)return {active:false};const e=ends(active.target),tx=e.end.x-e.start.x,tz=e.end.z-e.start.z,len=Math.max(.001,Math.hypot(tx,tz));active.duration+=dt;active.progress+=Math.max(0,state.speed||0)*dt/len*active.direction;active.balance=clamp(damp(active.balance,0,3.2*(powered?1.25:1),dt)+(Number(steer)||0)*.40*dt,-1,1);const t=clamp(active.progress,0,1);state.x=e.start.x+tx*t;state.y=e.start.y+(e.end.y-e.start.y)*t+.12;state.vx=tx/len*active.direction*(state.speed||0);const p=getRideProfile(state.rideMode);state.speed=Math.max(p.baseSpeed*.9,state.speed*(1-SKATEBOARD_TUNING.GRIND_FRICTION*dt));const s=ensureSkateboardState(state);s.grindDuration=active.duration;s.grindBalance=active.balance;if(Math.abs(active.balance)>=SKATEBOARD_TUNING.GRIND_FAIL)return {...exit(state,'balance-fail'),failed:true};if(active.progress<=0||active.progress>=1)return {...exit(state,'natural-exit'),natural:true};return {active:true,trick:active.trick,duration:active.duration,balance:active.balance};}
  function jumpOff(state,{popVelocity=6.8}={}){if(!active)return false;const out=exit(state,'jump-off');state.air=true;state.grounded=false;state.jumping=true;state.jumpSource='grind';state.vy=Math.max(state.vy||0,popVelocity);state.jumpVelocity=state.vy;return out;}
  function snapshot(){return {targetCount:targets.size,active:!!active,targetId:active?.target.id||'',trick:active?.trick||'',duration:active?.duration||0,balance:active?.balance||0};}
  return {register,unregister,reset,clear,tryEnter,step,jumpOff,exit,snapshot,get active(){return active;}};
}
export function getSkateboardGameplaySnapshot(state,grindSystem=null){const s=ensureSkateboardState(state);return {...s,events:undefined,grind:grindSystem?.snapshot?.()||null,displayedSpeedKmh:skateboardDisplaySpeedKmh(state.speed,state.rideMode),worldSpeedKmh:Math.round((state.speed||0)*3.6)};}
