import * as THREE from 'three';
const CAPACITY=640,clamp=THREE.MathUtils.clamp;
const rand=i=>{const x=Math.sin(i*127.1+311.7)*43758.5453;return x-Math.floor(x);};
export function createSnowParticles({scene,densityMultiplier=1}={}){
  const positions=new Float32Array(CAPACITY*3),alphas=new Float32Array(CAPACITY),sizes=new Float32Array(CAPACITY),types=new Float32Array(CAPACITY),velocities=new Float32Array(CAPACITY*3),ages=new Float32Array(CAPACITY),lives=new Float32Array(CAPACITY),active=new Uint8Array(CAPACITY);
  const geometry=new THREE.BufferGeometry(),positionAttribute=new THREE.BufferAttribute(positions,3),alphaAttribute=new THREE.BufferAttribute(alphas,1),sizeAttribute=new THREE.BufferAttribute(sizes,1),typeAttribute=new THREE.BufferAttribute(types,1);
  for(const a of [positionAttribute,alphaAttribute,sizeAttribute,typeAttribute])a.setUsage(THREE.DynamicDrawUsage);
  geometry.setAttribute('position',positionAttribute);geometry.setAttribute('aAlpha',alphaAttribute);geometry.setAttribute('aSize',sizeAttribute);geometry.setAttribute('aType',typeAttribute);
  const uniforms={tint:{value:new THREE.Color(0xffffff)}};
  const material=new THREE.ShaderMaterial({uniforms,transparent:true,depthWrite:false,
    vertexShader:['attribute float aAlpha;','attribute float aSize;','attribute float aType;','varying float vAlpha;','varying float vType;','void main(){','vAlpha=aAlpha;vType=aType;','vec4 mvPosition=modelViewMatrix*vec4(position,1.0);','gl_Position=projectionMatrix*mvPosition;','gl_PointSize=aSize*clamp(20.0/max(1.0,-mvPosition.z),.50,2.35);','}'].join('\n'),
    fragmentShader:['uniform vec3 tint;','varying float vAlpha;','varying float vType;','void main(){','vec2 p=gl_PointCoord-.5;float d=length(p);','float soft=1.0-smoothstep(.16,.50,d);','float crystal=1.0-smoothstep(.035,.18,abs(p.x+p.y*.42));','float powder=1.0-smoothstep(.05,.48,d);','float shape=mix(.76*soft+.24*crystal,powder,vType);','float a=vAlpha*shape;if(a<.006)discard;','vec3 c=mix(tint*1.02,tint*.95,vType*.45);','gl_FragColor=vec4(c,a);','#include <tonemapping_fragment>','#include <colorspace_fragment>','}'].join('\n')
  });
  const points=new THREE.Points(geometry,material);points.name='local-snow-vfx';points.frustumCulled=false;points.renderOrder=7;scene?.add(points);
  const contactA=new THREE.Vector3(),contactB=new THREE.Vector3();let cursor=0,serial=0,densityScale=clamp(Number(densityMultiplier)||1,0,1.4),emitBudget=0,speedBudget=0,previousEdge=0,previousLanding=0;
  function spawn(x,y,z,vx,vy,vz,size,life,alpha,type=0){const i=cursor++%CAPACITY,k=i*3;active[i]=1;ages[i]=0;lives[i]=Math.max(.12,life);positions[k]=x;positions[k+1]=y;positions[k+2]=z;velocities[k]=vx;velocities[k+1]=vy;velocities[k+2]=vz;sizes[i]=size;alphas[i]=alpha;types[i]=type;serial++;}
  function resolveContact(object,target,x,y,z){if(object?.isObject3D){object.updateWorldMatrix(true,false);target.set(0,0,.48);object.localToWorld(target);return target;}return target.set(x,y,z);}
  function emitFrom(origin,edge,speed01,board,intensity,powderDepth,sideBias=0){const r=rand(serial+17),r2=rand(serial+31),r3=rand(serial+47),carve=clamp(Math.abs(edge),0,1),dir=-Math.sign(edge||previousEdge||1),powder=r<.18+powderDepth*.68?1:0;spawn(origin.x+(r-.5)*(board?.62:.22)+sideBias,origin.y+.025+r2*.065,origin.z+.18+r3*.16,dir*(board?2.5:1.85)*(carve+.20)*intensity+(r-.5)*(board?1.05:.72),.34+r2*(.85+carve*.80+powderDepth*.48),1.35+speed01*3.9+r3*.9,(powder?6.4:4.3)+r2*(board?5.2:4.0)+speed01*1.8+powderDepth*2.2,.32+r*.36+powderDepth*.16,.14+carve*.32+speed01*.11+powderDepth*.12,powder);}
  function burst(count,x,y,z,edge,speed,rideMode,landing=false){const board=rideMode==='snowboard',speed01=clamp((speed-35)/50,0,1),strength=clamp(Math.abs(edge),.25,1),dir=-Math.sign(edge||previousEdge||1);for(let n=0;n<count;n++){const r=rand(serial+n*5+13),r2=rand(serial+n*7+29),r3=rand(serial+n*11+3),side=(r-.5)*(board?1.65:1.05);spawn(x+side,y+.035+r2*.13,z+.20+(r3-.5)*.35,dir*(board?2.8:2.15)*(.32+r*.92)+(r2-.5)*1.05,.55+r2*(landing?2.65:1.55),1.25+r3*(2.0+speed01*3.8),(landing?8.2:5.8)+r*5.2+(board?1.3:0),(landing?.76:.50)+r2*.36,(landing?.36:.23)+strength*.22,r>.44?1:0);}}
  function spray(dt,x,y,z,speed,edge,air,landingPulse,running=true,rideMode='ski',contacts=null){if(!running||densityScale<=.001){previousEdge=edge||0;previousLanding=landingPulse||0;return;}const speed01=clamp((speed-35)/50,0,1),carve=clamp(Math.abs(edge),0,1),powderDepth=clamp((Math.abs(x)-7.5)/5.8,0,1),board=rideMode==='snowboard',left=resolveContact(contacts?.[0],contactA,x-(board?0:.245),y,z+.48),right=resolveContact(contacts?.[1],contactB,x+(board?0:.245),y,z+.48);
    if(!air){const motion=.18+speed01*.44+carve*.86+powderDepth*.42;emitBudget+=dt*(10+speed01*24)*(board?1.18:1)*motion*densityScale;while(emitBudget>=1){emitBudget-=1;if(board){contactA.set((left.x+right.x)*.5,(left.y+right.y)*.5,(left.z+right.z)*.5);emitFrom(contactA,edge,speed01,true,.90+carve*.70,powderDepth,(rand(serial+71)-.5)*.46);}else{const useLeft=(serial&1)===0,origin=useLeft?left:right,outside=(useLeft?edge>0:edge<0)?1.26:.92;emitFrom(origin,edge,speed01,false,outside*(.76+carve*.62),powderDepth);}}
      if(speed01>.25&&carve<.22){speedBudget+=dt*(speed01-.25)*11*densityScale;while(speedBudget>=1){speedBudget-=1;const r=rand(serial+91),r2=rand(serial+117),origin=board?left:(r<.5?left:right);spawn(origin.x+(r-.5)*(board?.55:.18),origin.y+.025+r2*.04,origin.z+.16,(r-.5)*.45,.18+r*.34,1.0+speed01*2.6,3.2+r2*3.0,.26+r*.22,.08+speed01*.12,1);}}else speedBudget=Math.min(speedBudget,.5);
    }else{emitBudget=Math.min(emitBudget,.55);speedBudget=Math.min(speedBudget,.35);}
    const reversed=Math.sign(previousEdge)!==0&&Math.sign(edge)!==0&&Math.sign(previousEdge)!==Math.sign(edge)&&Math.abs(previousEdge)>.34&&Math.abs(edge)>.34;if(!air&&reversed)burst(Math.round((board?18:13)*densityScale),x,y,z,edge,speed,rideMode,false);
    if(landingPulse>.42&&previousLanding<=.42){const ls=clamp(landingPulse,0,1);burst(Math.round((16+ls*(board?24:19))*densityScale),x,y,z,edge||previousEdge,speed,rideMode,true);}previousEdge=edge||0;previousLanding=landingPulse||0;
  }
  function update(dt,worldSpeed=0){let pd=false,ad=false,sd=false;for(let i=0;i<CAPACITY;i++){if(!active[i])continue;ages[i]+=dt;if(ages[i]>=lives[i]){active[i]=0;alphas[i]=0;ad=true;continue;}const k=i*3;positions[k]+=velocities[k]*dt;positions[k+1]+=velocities[k+1]*dt;positions[k+2]+=(worldSpeed+velocities[k+2])*dt;velocities[k]*=Math.pow(.12,dt);velocities[k+1]-=(types[i]>.5?3.9:5.1)*dt;velocities[k+2]*=Math.pow(.30,dt);const t=ages[i]/lives[i];alphas[i]=Math.min(alphas[i]*Math.pow(.085,dt),(1-t)*.58);sizes[i]*=1+dt*(types[i]>.5?.58:.30);if(positions[k+2]>24||positions[k+1]<-1.2){active[i]=0;alphas[i]=0;}pd=ad=sd=true;}if(pd)positionAttribute.needsUpdate=true;if(ad)alphaAttribute.needsUpdate=true;if(sd)sizeAttribute.needsUpdate=true;}
  function reset(){active.fill(0);alphas.fill(0);ages.fill(0);lives.fill(0);emitBudget=speedBudget=0;previousEdge=0;previousLanding=0;alphaAttribute.needsUpdate=true;}
  function setTint(color){uniforms.tint.value.copy(color);}function setDensity(value=1){densityScale=clamp(Number(value)||0,0,1.4);points.visible=densityScale>.001;return densityScale;}function setEnabled(value=true){points.visible=!!value&&densityScale>.001;return points.visible;}function getDiagnostics(){let activeCount=0;for(const value of active)activeCount+=value;return {disabled:false,densityScale,active:activeCount,capacity:CAPACITY};}
  return {spray,update,reset,setTint,setDensity,setEnabled,getDiagnostics,setDensityMultiplier:setDensity,getDensityMultiplier:()=>densityScale};
}
